apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example
  namespace: demo-exploring-openshift
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
