apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-configmap-within-ns
  namespace: demo-exploring-openshift
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames:
      - my-config
    verbs:
      - get
